#!/usr/bin/env python3
"""Export: load best_rejection.keras, convert to INT8 TFLite, generate model_data.h"""
import os, sys, io, numpy as np, tensorflow as tf
from tensorflow import keras

if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "training", "finetuned_output")
FIRMWARE_DIR = os.path.join(PROJECT_ROOT, "esp32_firmware", "main")
N_FRAMES, N_MFCC = 49, 13

model_path = os.path.join(OUTPUT_DIR, "best_rejection.keras")
print(f"Loading model from {model_path}...")
model = keras.models.load_model(model_path)
print(f"  Model loaded: {model.count_params()} params")

# Trace the model to get a concrete function (works with Keras 3.x)
@tf.function(input_signature=[tf.TensorSpec(shape=[1, N_FRAMES, N_MFCC, 1], dtype=tf.float32)])
def serve(x):
    return model(x, training=False)

concrete = serve.get_concrete_function()

# INT8 quantization via concrete function
print("\nConverting to INT8 TFLite via concrete function...")

def representative_dataset():
    for _ in range(200):
        data = np.random.randn(1, N_FRAMES, N_MFCC, 1).astype(np.float32)
        yield [data]

converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type  = tf.int8
converter.inference_output_type = tf.int8

tflite_model = converter.convert()
tflite_path = os.path.join(OUTPUT_DIR, "hey_vaani_rejection.tflite")
with open(tflite_path, "wb") as f:
    f.write(tflite_model)
model_size_kb = len(tflite_model) / 1024
print(f"  TFLite saved: {tflite_path}")
print(f"  Model size: {len(tflite_model):,} bytes ({model_size_kb:.1f} KB)")

prior_size = 45616
size_change = len(tflite_model) - prior_size
if abs(size_change) > 2048:
    print(f"  WARNING: Size changed by {size_change:+,} bytes from prior {prior_size:,} byte baseline")
else:
    print(f"  Size stable (~{prior_size:,} byte baseline)")

# Generate model_data.h
best_threshold = 0.60
header_path = os.path.join(FIRMWARE_DIR, "model_data.h")
print(f"\nGenerating: {header_path}")

with open(header_path, "w") as f:
    f.write("// Auto-generated by finetune_rejection.py\n")
    f.write("// Hey Vaani KWS model - wake-word rejection fine-tune\n")
    f.write(f"// Model size: {len(tflite_model)} bytes ({model_size_kb:.1f} KB)\n")
    f.write(f"// Threshold: {best_threshold:.4f}\n")
    f.write(f"// Quantization: INT8\n")
    f.write("// Input: MFCC [49 x 13 x 1] (int8)\n")
    f.write("// Output: keyword_probability (int8)\n\n")
    f.write("#ifndef MODEL_DATA_H\n")
    f.write("#define MODEL_DATA_H\n\n")
    f.write(f"static const uint32_t g_model_data_len = {len(tflite_model)};\n\n")
    f.write("alignas(16) static const uint8_t g_model_data[] = {\n")
    for i, byte in enumerate(tflite_model):
        if i % 12 == 0:
            f.write("    ")
        f.write(f"0x{byte:02x}")
        if i < len(tflite_model) - 1:
            f.write(", ")
        if i % 12 == 11:
            f.write("\n")
    f.write("\n};\n\n")
    f.write("#endif // MODEL_DATA_H\n")

print(f"  model_data.h exported: {header_path}")
print(f"\nDone! Model: {len(tflite_model):,} bytes, Threshold: {best_threshold}")
