[platformio]
src_dir = main

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = partitions.csv
build_flags = -D NODE_ID=2

[env:esp32dev_node1]
extends = env:esp32dev
build_flags = -D NODE_ID=1
